build:
  nodes:
    analysis:
      dependencies:
        after:
          - composer require --dev squizlabs/php_codesniffer:2.9
      tests:
        override:
          - command: phpcs-run
            use_website_config: false              # use configuration from website editor
filter:
    excluded_paths:
        - tests/*
checks:
    php: true